

name: Build and Package Application

on:
  push:
    tags:
      - '*'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag name'
        required: false
        default: 'manual-trigger'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Install PHP Composer
        run: |
          docker run --rm -v "${{ github.workspace }}:/app" -w /app php:8.3-cli-alpine sh -c "
            apk add --no-cache curl \
            && curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer \
            && composer --version
          "

      - name: Delay before creating tar.gz
        run: sleep 5  # Adjust the delay time as needed

      - name: Create tar.gz package
        run: |
          tar -czvf application.tar.gz ${GITHUB_WORKSPACE}/.github/workflows ${GITHUB_WORKSPACE}/composer.json ${GITHUB_WORKSPACE}/skeleton

      - name: Configure Git
        run: |
          git config --global user.name "javeriakhn"
          git config --global user.email "javeriakashan97@gmail.com"

      - name: Push to build repository
        env:
          REPO_URL: https://github.com/javeriakhn/build-repo.git
          TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          git clone https://$TOKEN@github.com/javeriakhn/build-repo.git build-repo || true
          mv application.tar.gz build-repo/
          cd build-repo
          git add application.tar.gz
          git commit -m "Add build for tag ${{ github.ref }}"
          git push origin main
